### ISSUE TITLE
Cannot launch tool - System.ArgumentException: Empty path name is not legal.

### ISSUE THREAD

**Issue by harrymattison** [ara3d/bowerbird#1]
Installed Bowerbird.for.Revit.2023.msi
Launched Revit 2023
Attempt to launch Bowerbird

  Jrn.RibbonEvent "Execute external command:CustomCtrl_%CustomCtrl_%Add-Ins%Ara 3D%Bowerbird:Ara3D.Bowerbird.Revit.BowerbirdExternalCommand" 
' 1:< API_ERROR { : Assembly version conflict in some references in Ara3D.Bowerbird.Revit2023.dll assembly
'Addin's module Ara3D.Utils of version 1.4.2.0 conflicts with same preloaded module of version 1.4.4.0
'Addin's module Ara3D.Bowerbird.Interfaces of version 1.4.2.0 conflicts with same preloaded module of version 1.4.4.0
'Addin's module Ara3D.Services of version 1.4.2.0 conflicts with same preloaded module of version 1.4.4.0 } 
' 1:< ::89:: Delta VM: Avail -208 -> 134177456 MB, Used +245 -> 1116 MB; RAM: Avail -306 -> 1373 MB, Used +247 -> 1121 MB, Peak +4 -> 1121 MB 
' 1:< GUI Resource Usage GDI: Avail 9061, Used 939, User: Used 450 
' 1:< TaskDialog "System.ArgumentException: Empty path name is not legal.
'   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
'   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
'   at Roslyn.Utilities.StandardFileSystem.OpenFile(String filePath, FileMode mode, FileAccess access, FileShare share)
'   at Roslyn.Utilities.CommonCompilerFileSystemExtensions.OpenFileWithNormalizedException(ICommonCompilerFileSystem fileSystem, String filePath, FileMode fileMode, FileAccess fileAccess, FileShare fileShare)
'   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
'   at Ara3D.Utils.Roslyn.RoslynUtils.<>c.<ReferencesFromFiles>b__11_0(FilePath x)
'   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
'   at Ara3D.Utils.Roslyn.DirectoryCompiler.Compile()
'   at Ara3D.Bowerbird.Core.BowerbirdService.Compile()
'   at Ara3D.Bowerbird.WinForms.Net48.BowerbirdForm..ctor(IBowerbirdHost host, BowerbirdOptions options)
'   at Ara3D.Bowerbird.Revit.BowerbirdRevitApp.GetOrCreateWindow() in C:\Users\cdigg\git\ara3d\bowerbird\Revit2023\BowerbirdRevitApp.cs:line 80
'   at Ara3D.Bowerbird.Revit.BowerbirdRevitApp.Run(UIApplication application) in C:\Users\cdigg\git\ara3d\bowerbird\Revit2023\BowerbirdRevitApp.cs:line 116
'   at Ara3D.Bowerbird.Revit.BowerbirdExternalCommand.Execute(ExternalCommandData commandData, String& message, ElementSet elements) in C:\Users\cdigg\git\ara3d\bowerbird\Revit2023\BowerbirdExternalCommand.cs:line 20"

**Comment by harrymattison** [comment]
I first saw this exception for a custom add-in that I had created an installed on my computer. I un-registered all addins in C:\ProgramData\Autodesk\Revit\Addins\2023 and C:\Program Files\Autodesk\Revit 2023\AddIns 
Then the error happened for C:\Program Files\Autodesk\Revit 2023\SDA\bin\ICSharpCode.Core.WinForms.dll

https://github.com/ara3d/bowerbird/assets/2285720/9b894149-519d-471f-b15f-4a6ca1eb85b7

**Comment by cdiggins** [comment]
Thanks for sharing this, I will try to look into it this week.

**Comment by cdiggins** [comment]
I have made some progress on fixing this, I hope to have an update soon. Thanks for your patience!

**Comment by cdiggins** [comment]
@harrymattison  can you please verify that this is fixed in the newest release? Thanks!
